detect_abi = [
    {
        "inputs": [{"internalType": "bool", "name": "isLock", "type": "bool"}],
        "name": "changeLock",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newVerifyAddress", "type": "address"}],
        "name": "changeVerifyAddress",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "contractAddress", "type": "address"},
            {"internalType": "address", "name": "userAddress", "type": "address"},
            {"internalType": "uint256[]", "name": "tokenIds", "type": "uint256[]"},
            {"internalType": "uint256", "name": "nonce", "type": "uint256"},
            {"internalType": "bytes32", "name": "msgHash", "type": "bytes32"},
            {"internalType": "uint8", "name": "v", "type": "uint8"},
            {"internalType": "bytes32", "name": "r", "type": "bytes32"},
            {"internalType": "bytes32", "name": "s", "type": "bytes32"},
        ],
        "name": "claimNFT",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "userAddress", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "uint256", "name": "nonce", "type": "uint256"},
            {"internalType": "bytes32", "name": "msgHash", "type": "bytes32"},
            {"internalType": "uint8", "name": "v", "type": "uint8"},
            {"internalType": "bytes32", "name": "r", "type": "bytes32"},
            {"internalType": "bytes32", "name": "s", "type": "bytes32"},
        ],
        "name": "claimToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "contractAddress", "type": "address"},
            {"internalType": "uint256[]", "name": "tokenIds", "type": "uint256[]"},
        ],
        "name": "ownerClaimBack",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "geonAddress", "type": "address"},
            {"internalType": "address", "name": "geonRewarder", "type": "address"},
            {"internalType": "address", "name": "verifyAddress", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "contractAddress",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "claimer",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "tokenIds",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "blockStamp",
                "type": "uint256",
            },
        ],
        "name": "ClaimNFT",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "claimer",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "nonce",
                "type": "uint256",
            },
        ],
        "name": "ClaimToken",
        "type": "event",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "contractAddress", "type": "address"},
            {"internalType": "uint256[]", "name": "tokenIds", "type": "uint256[]"},
            {"internalType": "bool", "name": "isContinue", "type": "bool"},
        ],
        "name": "detectNFT",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "contractAddress",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "detecter",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "tokenIds",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "bool",
                "name": "isContinue",
                "type": "bool",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "blockStamp",
                "type": "uint256",
            },
        ],
        "name": "DetectNFT",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "contractAddress",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "tokenIds",
                "type": "uint256[]",
            },
        ],
        "name": "OwnerClaimBack",
        "type": "event",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "contractAddress", "type": "address"},
            {"internalType": "uint256[]", "name": "tokenIds", "type": "uint256[]"},
            {"internalType": "address[]", "name": "toAddresses", "type": "address[]"},
        ],
        "name": "ownerClaimTo",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "contractAddress",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "tokenIds",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "address[]",
                "name": "toAddresses",
                "type": "address[]",
            },
        ],
        "name": "OwnerClaimTo",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "previousOwner",
                "type": "address",
            },
            {
                "indexed": True,
                "internalType": "address",
                "name": "newOwner",
                "type": "address",
            },
        ],
        "name": "OwnershipTransferred",
        "type": "event",
    },
    {
        "inputs": [],
        "name": "renounceOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "_geon",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "_geonProvider",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "_verifyAddress",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "", "type": "address"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
        ],
        "name": "nftOwner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "", "type": "address"},
            {"internalType": "address", "name": "", "type": "address"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "bytes", "name": "", "type": "bytes"},
        ],
        "name": "onERC721Received",
        "outputs": [{"internalType": "bytes4", "name": "", "type": "bytes4"}],
        "stateMutability": "pure",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "", "type": "address"}],
        "name": "userNonce",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
]
