# Generated by Django 3.2.12 on 2022-02-17 10:43

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("geoname_id", models.IntegerField(primary_key=True, serialize=False)),
                ("locale_code", models.TextField()),
                ("continent_code", models.TextField(null=True)),
                ("continent_name", models.TextField(null=True)),
                ("country_iso_code", models.TextField(null=True)),
                ("country_name", models.TextField(null=True)),
                ("is_in_european_union", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="NetWork",
            fields=[
                (
                    "network",
                    models.GenericIPAddressField(
                        db_column="network",
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "represented_country_geoname_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("is_anonymous_proxy", models.BooleanField(default=False)),
                ("is_satellite_provider", models.BooleanField(default=False)),
                (
                    "geoname_id",
                    models.ForeignKey(
                        db_column="geoname_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="geoip.location",
                    ),
                ),
                (
                    "registered_cid",
                    models.ForeignKey(
                        db_column="registered_country_geoname_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="qcountry",
                        to="geoip.location",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="network",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["network"], name="network", opclasses=["inet_ops"]
            ),
        ),
    ]
